<!DOCTYPE html>
<html>
<head>
	<title>slider</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="slider created with cssSlider, a free wizard program that helps you easily generate beautiful web slideshow" />

	
</head>
<body style="background-color:#d7d7d7; margin: auto; text-align: center;">

		<!-- Start cssSlider.com -->
		<!-- Generated by cssSlider.com 2.1 -->
		<link rel="stylesheet" href="slider_files/csss_engine1/style.css">
		<!--[if IE]><link rel="stylesheet" href="slider_files/csss_engine1/ie.css"><![endif]-->
		<!--[if lte IE 9]><script type="text/javascript" src="slider_files/csss_engine1/ie.js"></script><![endif]-->
		 <div class='csslider1 autoplay '>
		<input name="cs_anchor1" id='cs_slide1_0' type="radio" class='cs_anchor slide' >
		<input name="cs_anchor1" id='cs_slide1_1' type="radio" class='cs_anchor slide' >
		<input name="cs_anchor1" id='cs_play1' type="radio" class='cs_anchor' checked>
		<input name="cs_anchor1" id='cs_pause1_0' type="radio" class='cs_anchor pause'>
		<input name="cs_anchor1" id='cs_pause1_1' type="radio" class='cs_anchor pause'>
		<ul>
			<li class="cs_skeleton"><img src="slider_files/csss_images1/slide1.jpg" style="width: 100%;"></li>
			<li class='num0 img slide'> <img src='assets/images/slider/slider1' alt='slide1' title='slide1' /></li>
			<li class='num1 img slide'> <img src='slider_files/csss_images1/slide2.jpg' alt='slide2' title='slide2' /></li>
		</ul><div class="cs_engine"><a href="http://cssslider.com">cssslider.com</a> by cssSlider.com v2.1</div>
		<div class='cs_description'>
			<label class='num0'><span class="cs_title"><span class="cs_wrapper">slide1</span></span><br/><span class="cs_descr"><span class="cs_wrapper">hchd
</span></span></label>
			<label class='num1'><span class="cs_title"><span class="cs_wrapper">slide2</span></span></label>
		</div>
		<div class='cs_play_pause'>
			<label class='cs_play' for='cs_play1'><span><i></i><b></b></span></label>
			<label class='cs_pause num0' for='cs_pause1_0'><span><i></i><b></b></span></label>
			<label class='cs_pause num1' for='cs_pause1_1'><span><i></i><b></b></span></label>
			</div>
		<div class='cs_arrowprev'>
			<label class='num0' for='cs_slide1_0'><span><i></i><b></b></span></label>
			<label class='num1' for='cs_slide1_1'><span><i></i><b></b></span></label>
		</div>
		<div class='cs_arrownext'>
			<label class='num0' for='cs_slide1_0'><span><i></i><b></b></span></label>
			<label class='num1' for='cs_slide1_1'><span><i></i><b></b></span></label>
		</div>
		<div class='cs_bullets'>
			<label class='num0' for='cs_slide1_0'> <span class='cs_point'></span>
				<span class='cs_thumb'><img src='slider_files/csss_tooltips1/slide1.jpg' alt='slide1' title='slide1' /></span></label>
			<label class='num1' for='cs_slide1_1'> <span class='cs_point'></span>
				<span class='cs_thumb'><img src='slider_files/csss_tooltips1/slide2.jpg' alt='slide2' title='slide2' /></span></label>
		</div>
		</div>
		<!-- End cssSlider.com -->
	
		
</body>
</html>